### ISSUE TITLE
A config to enable the mod for player only

### ISSUE THREAD

**Issue by guillaumearm** [Shovinus/ChopDownUpdated#10]
It could be very convenient to add a configuration field to enable the mod only when a player chop a tree (not a machine for example)

That would make automations with other mods easier. (e.g. Plant gatherer from industrial foregoing)

**Comment by Shovinus** [comment]
I was sure I had already fixed that because I discovered the problem before, you on the latest version?

On 21 May 2018 17:41, Guillaume ARM <notifications@github.com> wrote:

It could be very convenient to add a configuration field to enable the mod only when a player chop a tree (not a machine for example)

That would make automations with other mods easier. (e.g. Plant gatherer from industrial foregoing)

**Comment by guillaumearm** [comment]
Yes I'm using `ChopDownUpdater v1.0.9` for `minecraft 1.12.2+`

I'm using `Industrial Foregoing v1.9.0-163` (`minecraft 1.12.2` too)

**Comment by Shovinus** [comment]
I will look again, I thought I had solved by making it so if the player position was 0,0,0 then don't do the chop because most fake players don't set this and so it defaults to 0,0,0. The issue I had was getting foregoing to work in dev environment.

On 21 May 2018 18:17, Guillaume ARM <notifications@github.com> wrote:

Yes I'm using ChopDownUpdater v1.0.9 for minecraft 1.12.2+

I'm using Industrial Foregoing v1.9.0-163 (minecraft 1.12.2 too)

**Comment by guillaumearm** [comment]
Hmmm, are you sure industrial foregoing use fake players for doing that kind of things ?

**Comment by Shovinus** [comment]
Not 100% but my code relies on a given player as it uses the player to a) calculate the drop direction, and b) determine debug effects like makeGlass which are only usable by admin. So if no player is passed I would have expected an error tbh.

On 21 May 2018 18:52, Guillaume ARM <notifications@github.com> wrote:

Hmmm, are you sure industrial foregoing use fake players for doing that kind of things ?

**Comment by Shovinus** [comment]
691ab0d9fd59bf9c96a0423dc80dbc148c7ed412
Fixes (though forgot to put in commit message)
